name: flutter_pos
description: Offline POS Application with Bluetooth Printer Support
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  sqflite: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.1
  flutter_bluetooth_serial: ^0.4.0
  esc_pos_utils: ^1.1.0
  esc_pos_bluetooth: ^0.4.1
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
